import type { Metadata } from "next";
import "./globals.css";
import styles from "./layout.module.css";
import TopNavigation from "@components/navigation/TopNavigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <TopNavigation />
        <main className={styles.container}>{children}</main>
        <footer>
          <p>© 2024 Kia Motors</p>
        </footer>
      </body>
    </html>
  );
}
