// import type { Metadata } from "next";
import "@app/globals.css";
import styles from "@app/layout.module.css";
import TopNavigation from "@components/navigation/TopNavigation";
import Footer from "@components/footer/Footer";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <TopNavigation />
        <main className={styles.container}>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
